name: mapkit_js
description: Dart implementation of Apple's MapKitJS. Embedding Apple Maps on the Web.
version: 0.0.1
homepage: https://github.com/zuvola/mapkit_js

environment:
  sdk: ^3.3.3

dependencies:
  web: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
